name=Arduino_WireGuard
version=0.1.0
author=Arduino
maintainer=Arduino <info@arduino.cc>
sentence=Enables WireGuard VPN connections
paragraph=With this library you can create WireGuard VPN tunnels over an existing network connection.
category=Communication
url=https://github.com/arduino/ArduinoCore-zephyr/tree/master/libraries/Arduino_WireGuard
architectures=zephyr,zephyr_main,zephyr_contrib
includes=WireGuard.h
